### ISSUE TITLE
Add Starred tab link to profile page

### ISSUE THREAD

**Issue by leewp14** [Kir-Antipov/GitHub-Defreshed#11]
Not sure if this is achievable... but I felt like having the Stars tab back in the profile page instead on the left sidebar. Just a hyperlink tab would be good. 

Anyway, this really made my day! This is really something soooooo great haha xD Can't resist my joy when I saw the old UI back.

**Comment by Kir-Antipov** [comment]
> Anyway, this really made my day! This is really something soooooo great haha xD Can't resist my joy when I saw the old UI back.

I'm very pleased that you like my work, thank you so much for such wonderful words! :3

> Not sure if this is achievable

Everything is achievable here! :)
I made really simple and extensible script to manipulate any details of the GitHub GUI, so yes, we can change everything and everywhere. I have some plans about profile page in my mind, but current "roadmap" looks something like:

1) Wait until the "Latest commit design update" exits the preview and update the script for it (#7)
2) Then I want to work on the idea of ​​bringing back the old CSS styles, because at the moment I'm only "antialiasing" some overly rounded corners
3) And then we can finally go beyond the repository page and start returning the old GUI elsewhere (including the profile page)

Anyway, it would be very nice of you to find someone's profile page(s) in the Wayback machine so that it would be easier for me to get everything back :)
And also feel free to make a pull request if you decide to do it yourself while I'm working on the previous points! To get started, you can take a look at an example of a simple fixer like [this](https://github.com/Kir-Antipov/GitHub-Defreshed/blob/master/src/fixers/topics-fixer.js), which drags the repository topics from the right column back to the top.

**Comment by leewp14** [comment]
Thanks for the reply and the information!
I hope I could help on this, hopefully when I'm free. Was extremely busy with my academic thus don't get a chance to play with it for now xD

Anyway, here is a link to a GitHub profile in Wayback machine, hope it helps!
https://web.archive.org/web/*/github.com/CHEF-KOCH

**Comment by Kir-Antipov** [comment]
> Anyway, here is a link to a GitHub profile in Wayback machine, hope it helps!

Thank you! It will help a lot!

**Comment by Kir-Antipov** [comment]
@leewp14, it's been a while, but there's good news for you! :)

![preview](https://user-images.githubusercontent.com/40232067/88447868-a635e480-ce40-11ea-8c0a-ca93eb7b894e.png)

Working on a profile page, I think it will be ready in a couple of days :)

**Comment by Kir-Antipov** [comment]
Implemented in `v2.0.0`, don't forget to update your script version
