### ISSUE TITLE
Request: Non-minified userscript

### ISSUE THREAD

**Issue by StaticPH** [Kir-Antipov/GitHub-Defreshed#18]
I don't suppose you'd be willing to provide us with a version of the userscript that hasn't been minified?
Yes, users who want to make adjustments could take the time to reformat and analyze the script themselves, or just write their own from scratch, but both of those seem rather wasteful when there's already an open-source project that does 99% of what you want it to.
It's just so much easier to figure out what's what if everything has intelligible and informative names.

**Comment by Kir-Antipov** [comment]
Bruh. I didn't really get it. Why would anyone need this when the project literally has the open source code?

**Comment by Kir-Antipov** [comment]
Just believe me, digging through unminified Webpack exhaust is not much nicer than digging into minified one. And there's no need in it: you can just modify the sources and run `npm run build`, that's it.

Or better yet, you can simply create a feature request here ¯\\_(ツ)_/¯

**Comment by StaticPH** [comment]
I suppose... as far as actual changes I might have wanted to make, I'm talking about things like changing delays or shifting offsets; it probably wouldn't make sense to include such user-specific tweaks in the upstream.
By the way, I know it's not relevant to my initial question, but is it normal for your script to hang for several seconds while loading a user's profile page if you try to scroll _just_ after the page loads, with the old css config setting enabled?

**Comment by Kir-Antipov** [comment]
I think, it would be much easier for you to make a fork, cause you still need to keep the script in actual state, and if you or your userscript manager will update GitHub-Defreshed, you'll just lost everything you've manually edited

> is it normal for your script to hang for several seconds while loading a user's profile page if you try to scroll just after the page loads

Hm. Can not reproduce this. Could you provide an example?

**Comment by StaticPH** [comment]
With Chromium 72 Portable, using ViolentMonkey as my userscript manager.
Note first the difference in the time spent on scripting during page load.
In both cases, I immediately started using the scroll wheel on my mouse upon refreshing the page. You can see purple segments on the input graph starting to appear when the page first responds to the scroll wheel movement.
<details>
<summary>Without old css setting</summary>
![image](https://user-images.githubusercontent.com/7786502/89204585-582d8900-d584-11ea-8817-b41041dd0ac2.png)

</details>

<details>
<summary>With old css setting</summary>
![image](https://user-images.githubusercontent.com/7786502/89202985-d0df1600-d581-11ea-913d-3cf8b77d0aac.png)

</details>

**Comment by Kir-Antipov** [comment]
@StaticPH, well, it's something really strange and case-specific, and I don't think that I can even reproduce it by myself cause I can't even find Chromium 72 Portable binaries or sources. It seems like it's an outdated version since 84-86 versions are mentioned everywhere currently.

I have a hunch that this is caused by the preloader, but it's made in pure css, which should not affect site usability at all. All that the "Use old css styles" setting does is inject an extra `<style>` block into the page, this shouldn't affect performance in any noticeable way. And it works fine for all popular browsers I know (from Safari to Firefox)

**Comment by Kir-Antipov** [comment]
Try [GitHub-Defreshed 2.0.5](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v2.0.5), it's currently broken a little bit, but this should help to understand if the preloader is the root of the problem.

**Comment by Kir-Antipov** [comment]
Well, I needed a build that would preserve names of classes and functions for some debug purposes and just remembered this issue. I think this is exactly what you asked for.

I still do not understand why it's easier for you to make changes to the messy webpack build rather than to the project itself, but from now on the newest debug build will always be available [here](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/latest/download/github-defreshed.debug.user.js)
