### ISSUE TITLE
Slimmer toolbars on repository page

### ISSUE THREAD

**Issue by MrNaif2018** [Kir-Antipov/GitHub-Defreshed#33]
## Description

I am not 100% sure, but few updates back I have noticed that all toolbars (showing latest commit, issue filter, etc.) are now slimmer than before (looks like removed paddings). It was not so in the previous versions, and also not in the original github UI. Sorry if I missed some change, but I definitely remember it was not so before, see the screenshots below.

## Screenshot

( Showing on my own repo, as I don't have any other screenshots from older versions of the script)

**Current toolbars:**

In the repo page:

![изображение](https://user-images.githubusercontent.com/39452697/113473477-65cc4300-9472-11eb-8a5f-0bbfab7d361a.png)

In the issues filter:

![изображение](https://user-images.githubusercontent.com/39452697/113473484-71b80500-9472-11eb-8fc4-13e953f71268.png)

Pull requests filter:

![изображение](https://user-images.githubusercontent.com/39452697/113473496-82687b00-9472-11eb-859d-040e5e1ad6be.png)

**How was it back then:**

At the initial versions of the script:

![изображение](https://user-images.githubusercontent.com/39452697/113473534-be9bdb80-9472-11eb-9a88-befdc46340ba.png)

Few months after the creation of the script:

![изображение](https://user-images.githubusercontent.com/39452697/113473521-aa57de80-9472-11eb-804a-62aa2414bd92.png)

## Other information

- **Link to page with the issue**: Any repository page, for example, my [repo](https://github.com/bitcartcc/bitcart)
- **Web Archive example**: Web archive seems to be unavailable now, see the screenshots above, will add an example when it's back up, but it's easy to find out
- **Browser**: Firefox 86.0, tried in Chrome 89.0.4389.90, same issue
- **Operating System**: Linux Mint 20.1 XFCE 64 bit
- **GitHub-Defreshed version**: 4.2.1

**Comment by Kir-Antipov** [comment]
Not a bug, but a feature :)

Yep, toolbars definitely lost a few pixels, but it was intentional. At the moment, with the help of Microsoft, they have grown to insane proportions:

![wtf](https://user-images.githubusercontent.com/40232067/113482069-9aa5bd80-94a5-11eb-87e1-69dc38b2a6a4.png)

And I really don't know why these guys are so much into wasting space...

> Web archive seems to be unavailable now, see the screenshots above, will add an example when it's back up, but it's easy to find out

Well, it's up now (at least for me), so I've just used [the link](http://web.archive.org/web/20200131010925/https://github.com/Cxbx-Reloaded/Cxbx-Reloaded) you gave me earlier:

![before](https://user-images.githubusercontent.com/40232067/113482103-bc9f4000-94a5-11eb-81df-7ae8288dc500.png)

With GitHub-Defreshed:

![now](https://user-images.githubusercontent.com/40232067/113482128-dd679580-94a5-11eb-8226-37012cc0f8c4.png)

So, yeah, it seems like I overdid slimming a little bit (`38.3` < `43.6`), but did I really? As for me, even "golden age" toolbar was kinda *plumper* than it should be. Anyway, as always, I'm open for suggestions, so I can make this thing optional :)

**Comment by MrNaif2018** [comment]
Thank you for replying! Yeah, I checked the recent UI and it's now ridiculously wide. Not really an issue to me, just something I noticed and wanted to let you know (I am just used to old style visually).
I think it is fine, but if you add this option it would be great. Don't want to request some features which aren't very important and are very subjective.
I will close the issue, it's up to you whether to add this feature or not, this script is already helping lots of people!
Thank you very much.

**Comment by Kir-Antipov** [comment]
> something I noticed and wanted to let you know

Thanks a lot! Sometimes it's really helpful as I don't always notice changes made by Microsoft :)

> Don't want to request some features which aren't very important and are very subjective

Nothing to worry about: a lot of stuff about UI in general is "not very important" and "subjective", but all these small features form an interface we're comfortable with

> it's up to you whether to add this feature or not

I think I'll ship it with a new version. Right now I have some things to do, so it will be a week or something like this

**Comment by MrNaif2018** [comment]
Not stale (:

**Comment by Kir-Antipov** [comment]
Usually `@stale` closes posts, the authors of which have disappeared and stopped responding. In my case, it's a little bit different:

![do something...](https://user-images.githubusercontent.com/40232067/115416857-cbedef80-a200-11eb-81e4-c50328f9daf9.png)
