### ISSUE TITLE
Preview changes to edited markdown files are not working

### ISSUE THREAD

**Issue by SvenErik1968** [Kir-Antipov/GitHub-Defreshed#9]
When I edit a markdown file, and click on the Preview changes, nothing happens. Also, the Commit changes button appears to be inactive. In order to preview or commit changes, I have to deactivate the  GitHub-Defreshed (v 1.4.5) script in Tapermonkey.

**Comment by Kir-Antipov** [comment]
Hm, yes, markdown editor seems broken. Bruh. Will fix it somehow :)

Thanks for your report!

**Comment by Kir-Antipov** [comment]
Just found a problem. I'll update the script in few hours

**Comment by Kir-Antipov** [comment]
Hi! I'm sorry for this delay, but now editors (Markdown, JSON and so on) work as they should (don't forget to update your script to [v1.5.0](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v1.5.0))

And thanks again for the report, it helped me find a mistake due to which the editors didn't work, which in turn is associated with another small problem that I'll solve in the future :)
